filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /apim-logs/apim_metrics.log
    # multiline:
    #   pattern: '^\['
    #   negate: true
    #   match: after

output.logstash:
  hosts: ["logstash:5044"]

logging.level: info