input {
  beats {
    port => 5044
  }
}

filter {
  if "apimMetrics" in [message] {
    grok {
      match => {
        "message" => "\[%{TIMESTAMP_ISO8601:apim_timestamp}\]\s+%{LOGLEVEL:level}\s+\{%{DATA:class}\}\s+-\s+apimMetrics:\s+%{DATA:metric_name},\s+properties\s+:%{GREEDYDATA:properties_raw}"
      }
    }
    json {
      source => "properties_raw"
      target => "event"
      remove_field => ["properties_raw"]
    }
    date {
      match => ["apim_timestamp", "yyyy-MM-dd HH:mm:ss,SSS"]
      target => "@timestamp"
      remove_field => ["apim_timestamp"]
    }
    mutate {
      remove_field => ["message", "class", "level", "agent", "ecs"]
    }
  } else {
    drop {}
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "apim-analytics-%{+YYYY.MM.dd}"
  }
  # Útil para depurar durante las pruebas
  stdout {
    codec => rubydebug
  }
}